# build_db_from_txt.py
# Builds ChromaDB from already-saved ocr_raw_output.txt
# Much faster than re-running OCR on the PDF every time!
#
# REQUIRES: ocr_raw_output.txt (generated by build_db_from_pdf.py)
#
# USAGE:
#   conda activate rag_env
#   cd D:\hoc\project\rag-legal-assistant-master
#   python database/build_db_from_txt.py

import os
import re
import shutil
from langchain.schema import Document
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

# =========================
# CONFIG
# =========================
BASE_DIR     = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TXT_PATH     = os.path.join(BASE_DIR, "ocr_raw_output.txt")
DB_PATH      = os.path.join(BASE_DIR, "chroma_db")
INSERT_BATCH = 32

# =========================
# STEP 1: LOAD TXT FILE
# =========================
print(f"Loading OCR text from: {TXT_PATH}")

if not os.path.exists(TXT_PATH):
    print("❌ ERROR: ocr_raw_output.txt not found!")
    print("   Please run build_db_from_pdf.py first to generate it.")
    exit(1)

with open(TXT_PATH, "r", encoding="utf-8") as f:
    raw = f.read()

print(f"   File size: {len(raw):,} characters")

# =========================
# STEP 2: STRIP PAGE MARKERS
# ─────────────────────────
# Remove "=== TRANG X ===" markers that were added
# by build_db_from_pdf.py, then join into one clean text
# =========================
print("Cleaning page markers...")

# Remove === TRANG X === lines
cleaned = re.sub(r'\n*=== TRANG \d+ ===\n*', '\n', raw)

# Clean up excessive whitespace
cleaned = re.sub(r'\n{3,}', '\n\n', cleaned)
cleaned = re.sub(r'[ \t]+', ' ', cleaned).strip()

print(f"   Clean text: {len(cleaned):,} characters")

# =========================
# STEP 3: SEGMENT BY ARTICLE
# ─────────────────────────
# Split on "Điều X." — full articles including
# content that spanned multiple PDF pages
# =========================
print("Segmenting by legal article (Điều)...")

pattern    = r'(?:(?:^|\n)(?=Điều\s+\d+[a-z]?[.,]\s))'
raw_splits = re.split(pattern, cleaned, flags=re.MULTILINE)

# Filter noise
segments_raw = [s.strip() for s in raw_splits if len(s.strip()) > 50]

print(f"Found {len(segments_raw)} legal article segments.")

# Fallback: fixed-size chunks if article detection fails
if len(segments_raw) < 10:
    print("Warning: few articles detected — using fixed-size chunking as fallback.")
    chunk_size   = 3000
    overlap      = 300
    segments_raw = []
    i = 0
    while i < len(cleaned):
        segments_raw.append(cleaned[i:i + chunk_size])
        i += chunk_size - overlap
    print(f"  Created {len(segments_raw)} chunks.")

# =========================
# STEP 4: BUILD DOCUMENTS
# =========================
print("Building document objects...")

docs = []
for i, seg in enumerate(segments_raw):
    text = seg.strip()
    if len(text) < 30:
        continue

    # Extract article number
    article_match = re.match(r'Điều\s+(\d+[a-z]?)[\.\s]', text)
    article_num   = article_match.group(1) if article_match else str(i + 1)

    # First non-empty line as title
    lines = [l.strip() for l in text.split('\n') if l.strip()]
    title = lines[0][:120] if lines else f"Điều {article_num}"

    docs.append(Document(
        page_content=text,          # full article text, no limit
        metadata={
            "so_ky_hieu":     "59/2020/QH14",
            "loai_van_ban":   "Luật",
            "title":          title,
            "article_number": article_num,
            "nguon_thu_thap": "Luật Doanh nghiệp 2020",
            "char_count":     len(text),
            "segment_index":  i,
        }
    ))

print(f"Built {len(docs)} document segments.")
if docs:
    avg_len = sum(len(d.page_content) for d in docs) // len(docs)
    max_len = max(len(d.page_content) for d in docs)
    min_len = min(len(d.page_content) for d in docs)
    print(f"  Average chars per article : {avg_len:,}")
    print(f"  Longest  article          : {max_len:,} chars")
    print(f"  Shortest article          : {min_len:,} chars")

# =========================
# STEP 5: EMBED + CHROMADB
# =========================
print("\nLoading embedding model (BAAI/bge-small-en-v1.5)...")
embedding = HuggingFaceEmbeddings(model_name="BAAI/bge-small-en-v1.5")

print(f"Building ChromaDB at: {DB_PATH}")

if os.path.exists(DB_PATH):
    print("  Clearing old ChromaDB...")
    shutil.rmtree(DB_PATH)

vs = None
for i in range(0, len(docs), INSERT_BATCH):
    chunk = docs[i:i + INSERT_BATCH]
    if vs is None:
        vs = Chroma.from_documents(chunk, embedding, persist_directory=DB_PATH)
    else:
        vs.add_documents(chunk)
    print(f"  Indexed {min(i + INSERT_BATCH, len(docs))}/{len(docs)} segments")

print("\n✅ DONE!")
print(f"   Articles indexed  : {len(docs)}")
print(f"   ChromaDB path     : {DB_PATH}")
print("\nNext step: python app.py")